### ISSUE TITLE
State of the projet

### ISSUE THREAD

**Issue by arnaudbriche** [SparklineData/spark-druid-indexer#1]
Hi,

I'm really interested in the state of the project as I'd like to use Druid Batch Indexing but I'm very reluctant to deploy a Hadoop cluster for this sole purpose.

Is this working ? Will be maintained in the future ? Is there any doc on how to use it ?

Regards,

**Comment by hbutani** [comment]
Hi,

First of all sorry, i missed this until now. Wasn't expecting interest in this at such an early stage. 
I am hoping to have a procedure in place for indexing in a few days. Stay tuned for a detailed example on how to index tpch.  This indexing functionality is meant to be used with the spark-druid-olap project which then uses the index to speedup queries against the indexed star schema.
Feel free to reach out to me if you want to discuss more details.

regards,
Harish

**Comment by hbutani** [comment]
This functionality is available as create/insert of OLAP Indexes in our [SNAP BI Platform](https://www.linkedin.com/pulse/integrated-business-intelligence-big-data-stacks-harish-butani)
